package com.example.tmpSpringBoot.dto.generator;

import java.util.Date;

public class CommonMst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.common_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String commonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.common_group
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String commonGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.common_name
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String commonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.common_value1
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String commonValue1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.common_value2
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String commonValue2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.update_datetime
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Date updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_mst.version
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.common_id
     *
     * @return the value of common_mst.common_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getCommonId() {
        return commonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.common_id
     *
     * @param commonId the value for common_mst.common_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setCommonId(String commonId) {
        this.commonId = commonId == null ? null : commonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.common_group
     *
     * @return the value of common_mst.common_group
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getCommonGroup() {
        return commonGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.common_group
     *
     * @param commonGroup the value for common_mst.common_group
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setCommonGroup(String commonGroup) {
        this.commonGroup = commonGroup == null ? null : commonGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.common_name
     *
     * @return the value of common_mst.common_name
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.common_name
     *
     * @param commonName the value for common_mst.common_name
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setCommonName(String commonName) {
        this.commonName = commonName == null ? null : commonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.common_value1
     *
     * @return the value of common_mst.common_value1
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getCommonValue1() {
        return commonValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.common_value1
     *
     * @param commonValue1 the value for common_mst.common_value1
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setCommonValue1(String commonValue1) {
        this.commonValue1 = commonValue1 == null ? null : commonValue1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.common_value2
     *
     * @return the value of common_mst.common_value2
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getCommonValue2() {
        return commonValue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.common_value2
     *
     * @param commonValue2 the value for common_mst.common_value2
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setCommonValue2(String commonValue2) {
        this.commonValue2 = commonValue2 == null ? null : commonValue2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.update_datetime
     *
     * @return the value of common_mst.update_datetime
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.update_datetime
     *
     * @param updateDatetime the value for common_mst.update_datetime
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_mst.version
     *
     * @return the value of common_mst.version
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_mst.version
     *
     * @param version the value for common_mst.version
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}