package com.example.tmpSpringBoot.dto.generator;

import java.util.Date;

public class UserMst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.user_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.password
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.user_name
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.secret_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String secretId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.secret_answer
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private String secretAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.error_password
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Short errorPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.lock
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Boolean lock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.authority
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Short authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.update_datetime
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Date updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.version
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.user_id
     *
     * @return the value of user_mst.user_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.user_id
     *
     * @param userId the value for user_mst.user_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.password
     *
     * @return the value of user_mst.password
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.password
     *
     * @param password the value for user_mst.password
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.user_name
     *
     * @return the value of user_mst.user_name
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.user_name
     *
     * @param userName the value for user_mst.user_name
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.secret_id
     *
     * @return the value of user_mst.secret_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getSecretId() {
        return secretId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.secret_id
     *
     * @param secretId the value for user_mst.secret_id
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setSecretId(String secretId) {
        this.secretId = secretId == null ? null : secretId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.secret_answer
     *
     * @return the value of user_mst.secret_answer
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public String getSecretAnswer() {
        return secretAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.secret_answer
     *
     * @param secretAnswer the value for user_mst.secret_answer
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setSecretAnswer(String secretAnswer) {
        this.secretAnswer = secretAnswer == null ? null : secretAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.error_password
     *
     * @return the value of user_mst.error_password
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Short getErrorPassword() {
        return errorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.error_password
     *
     * @param errorPassword the value for user_mst.error_password
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setErrorPassword(Short errorPassword) {
        this.errorPassword = errorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.lock
     *
     * @return the value of user_mst.lock
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Boolean getLock() {
        return lock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.lock
     *
     * @param lock the value for user_mst.lock
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setLock(Boolean lock) {
        this.lock = lock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.authority
     *
     * @return the value of user_mst.authority
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Short getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.authority
     *
     * @param authority the value for user_mst.authority
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setAuthority(Short authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.update_datetime
     *
     * @return the value of user_mst.update_datetime
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.update_datetime
     *
     * @param updateDatetime the value for user_mst.update_datetime
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.version
     *
     * @return the value of user_mst.version
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.version
     *
     * @param version the value for user_mst.version
     *
     * @mbg.generated Fri Sep 09 00:49:13 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}